import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const [number, setNumber] = useState<string>("");

  return (
    <div className={styles.container}>
      <Head>
        <title>WhatsApp sin agendar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Envia un mensage por WhatsApp sin agendar el numero
        </h1>

        <div
          style={{ width: "100%", display: "flex", flexDirection: "column" }}
        >
          <input
            placeholder="Numero de celular"
            className={styles.phoneInput}
            value={number}
            onChange={(ev) => setNumber(ev.target.value)}
            type="number"
          />
          <a
            className={styles.phoneBtn}
            target="_blak"
            href={`https://api.whatsapp.com/send?phone=${number}`}
          >
            Enviar
          </a>
        </div>
      </main>
    </div>
  );
};

export default Home;
